import React,{useRef,useState,useEffect} from 'react';
import {login,signup,logout,requestPasswordRecovery,updateUser,acceptInvite} from '@netlify/identity';
import {X,BookOpen,Cloud,LogOut,ShieldCheck,LoaderCircle} from 'lucide-react';
import './account-modal.css';
import {AccountProfile} from './account-profile.jsx';
export function AccountModal({learning,close,switching=false}){
 const modal=useRef();
 const [profileBusy,setProfileBusy]=useState(false);
 const closeRef=useRef(close),busyRef=useRef(profileBusy);closeRef.current=close;busyRef.current=profileBusy;
 const canClose=()=>{if(!busyRef.current)closeRef.current();};
 const {user,settings,authCallback,setAuthCallback,setMessage}=learning;
 const callbackMode=authCallback?.type==='recovery'?'reset':authCallback?.type==='invite'?'reset':null;
 const showAccount=!!user&&!callbackMode&&!switching;
 const [mode,setMode]=useState(callbackMode||'login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const old=document.activeElement;modal.current?.querySelector('input,button')?.focus();const fn=e=>{if(e.key==='Escape')canClose();if(e.key==='Tab'){const items=[...modal.current.querySelectorAll('input,button')].filter(n=>!n.disabled);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',fn);return()=>{window.removeEventListener('keydown',fn);old?.focus();};},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{
  if(mode==='reset'){if(authCallback?.type==='invite')await acceptInvite(authCallback.token,password);else await updateUser({password});setAuthCallback(null);setMessage('密码已更新。');close();}
  else if(mode==='forgot'){await requestPasswordRecovery(email);setError('如果该邮箱已注册，你将收到密码恢复邮件。');}
  else if(mode==='signup'){const u=await signup(email,password,{full_name:name});if(u.confirmedAt){setMessage('注册成功，可以开始云端同步。');close();}else setError('请查收确认邮件，验证后登录。');}
  else{await login(email,password);setMessage('已登录，账号记录与游客记录分别保存。');close();}
 }catch(err){setError(err.status===401?'邮箱或密码不正确，请重新输入。':err.message||'操作失败，请稍后重试。');}finally{setBusy(false);setPassword('');}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)canClose();}}><section ref={modal} className="account-modal" role="dialog" aria-modal="true" aria-labelledby="account-title"><button className="modal-close" aria-label="关闭账号窗口" disabled={profileBusy} onClick={canClose}><X size={21}/></button><span className="brand-mark"><BookOpen size={24}/></span><h2 id="account-title">{showAccount?'我的学习账号':({login:switching?'切换学习账号':'继续你的法语之旅',signup:'创建学习账号',forgot:'找回密码',reset:'设置新密码'})[mode]}</h2>{showAccount?<><AccountProfile key={user.id} user={user} onBusy={setProfileBusy} onSaved={()=>setMessage('账号资料已更新。')}/><div className="modal-note profile-note"><Cloud size={20}/>昵称和头像随账号保存，重新登录后仍可使用。</div><button className="button full profile-logout" disabled={profileBusy} onClick={async()=>{await logout();setMessage('已退出，恢复游客学习记录。');close();}}><LogOut size={17}/>退出登录</button></>:settings===false?<><p>账号服务暂时不可用。可以继续游客学习，记录保存在本机，并支持导出备份。</p><button className="button primary full" onClick={close}>继续游客学习</button></>:<><p>{mode==='login'?(switching?'登录另一个账号，验证成功后切换；取消可保留当前账号。':'登录后，让手机和电脑共享学习进度。'):mode==='signup'?'现有游客记录仍会保留，登录后可手动导入。':'通过邮件验证后恢复访问。'}</p><form onSubmit={submit}>{mode==='signup'&&<label>昵称<input required value={name} maxLength={40} autoComplete="nickname" onChange={e=>setName(e.target.value)} placeholder="你的名字"/></label>}{mode!=='reset'&&<label>邮箱<input type="email" required value={email} autoComplete="email" onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoFocus/></label>}{mode!=='forgot'&&<label>密码<input type="password" required minLength={mode==='login'?1:8} value={password} autoComplete={mode==='login'?'current-password':'new-password'} onChange={e=>setPassword(e.target.value)} placeholder={mode==='login'?'输入密码':'至少 8 位'}/></label>}{mode==='login'&&<div className="account-remember-note"><ShieldCheck size={16}/><span>默认保持登录。下次打开自动恢复有效会话，无需重新输入密码。</span></div>}{error&&<p className="form-message" role="status">{error}</p>}<button className="button primary full" disabled={busy||settings===null} type="submit">{busy?<LoaderCircle size={18} className="spin"/>:null}{({login:'登录',signup:'注册',forgot:'发送恢复邮件',reset:'保存新密码'})[mode]}</button></form>{mode==='login'&&<div className="auth-links">{settings?.disableSignup===false&&<button onClick={()=>{setMode('signup');setError('');}}>创建账号</button>}<button onClick={()=>{setMode('forgot');setError('');}}>忘记密码？</button></div>}{mode!=='login'&&mode!=='reset'&&<button className="text-link center" onClick={()=>{setMode('login');setError('');}}>返回登录</button>}</>}</section></div>;
}
