import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,LayoutDashboard,CalendarDays,Shuffle,Library,ChartNoAxesCombined,ArrowRight,ChevronRight,ChevronLeft,Check,X,Cloud,CloudOff,Download,Upload,Search,Settings,LogIn,LogOut,GraduationCap,CheckCircle2,RotateCcw,ShieldCheck,Info,Menu,Plus,Mail,LoaderCircle,Sun,Moon,Monitor,ArrowUpRight} from 'lucide-react';
import {login,signup,logout,requestPasswordRecovery,updateUser,acceptInvite} from '@netlify/identity';
import {T,D,V,bank,ordinaryBank,titles,themeTitles,parts,dictionary,day,partName,fresh,currentAttempt,bookAction,makeDaily,touch,importRecord} from './engine';
import {useLearning} from './useLearning';
import './style.css';
import {AccountMenu} from './account-menu';

const navigation=[['home','学习首页',LayoutDashboard],['textbook','课本单词检测',BookOpen],['daily','每日单词检测',CalendarDays],['practice','普通词汇检测',Shuffle],['library','完整词库',Library],['records','学习记录',ChartNoAxesCombined]];
const pageTitles={home:'学习首页',textbook:'课本单词检测',daily:'每日单词检测',practice:'普通词汇检测',library:'完整词库',records:'学习记录',settings:'设置与备份'};
const route=()=>Object.hasOwn(pageTitles,location.hash.slice(2))?location.hash.slice(2):'home';
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function App(){
 const learning=useLearning(),{bundle,update,adopt,user,sync,settings,message,setMessage}=learning;
 const [page,setPage]=useState(route),[auth,setAuth]=useState(false),[theme,setTheme]=useState(()=>{try{return localStorage.getItem('edito-theme')||'light';}catch{return 'light';}});
 const [switchingAccount,setSwitchingAccount]=useState(false);
 function switchAccount(){setSwitchingAccount(true);setAuth(true);}
 function closeAccount(){setAuth(false);setSwitchingAccount(false);}
 async function signOut(){await logout();setMessage('已退出，恢复游客学习记录。');}
 const [active,setActive]=useState(()=>currentAttempt(bundle.main)?.id),[dailyProblem,setDailyProblem]=useState(''),[importing,setImporting]=useState(false),[libraryPart,setLibraryPart]=useState('all');
 const input=useRef(),dailyLaunch=useRef(false);const current=currentAttempt(bundle.main),allowed=D.eligible(bundle.main,bank);
 const totals=Object.values(bundle.main.stats).reduce((s,c)=>({good:s.good+c.good,bad:s.bad+c.bad}),{good:0,bad:0});
 useEffect(()=>{const fn=()=>setPage(route());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('edito-theme',theme);}catch{}},[theme]);
 useEffect(()=>{setActive(currentAttempt(bundle.main)?.id);},[bundle.main.current,bundle.main.completed]);
 useEffect(()=>{if(!bundle.main.attempts.some(a=>a.id===active))setActive(current?.id);},[bundle.main,active,current]);
 useEffect(()=>{if(learning.authCallback?.type==='recovery'||learning.authCallback?.type==='invite')setAuth(true);},[learning.authCallback]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),9000);return()=>clearTimeout(timer);},[message,setMessage]);
 function generateDaily(){const result=makeDaily(bundle);setDailyProblem(result.problem||'');if(!result.problem)adopt(result.state);}
 function go(next){if(next==='daily'&&page!==next&&sync!=='loading'){dailyLaunch.current=true;generateDaily();}if(next==='textbook')setActive(current?.id);location.hash='/'+next;setPage(next);window.scrollTo({top:0,behavior:'instant'});}
 useEffect(()=>{
  if(page!=='daily'||sync==='loading')return;
  if(!dailyLaunch.current){dailyLaunch.current=true;generateDaily();return;}
  if(bundle.daily&&!D.validRound(bundle.daily,bank,allowed)||!bundle.daily&&!D.problem(bank,allowed))generateDaily();
  const timer=setInterval(()=>{if(bundle.daily?.day!==day())generateDaily();},60000);
  return()=>clearInterval(timer);
 },[page,sync==='loading',allowed.join('|'),bundle.daily?.day]);
 useEffect(()=>{
  if(page!=='textbook')return;const a=bundle.main.attempts.find(a=>a.id===active);
  if(!a||bundle.main.completed||a.part!==bundle.main.order[bundle.main.current]||a.ids.some(id=>a.votes[id]!=='good'))return;
  const timer=setTimeout(()=>{update(s=>bookAction(s,a.id,'pass',null,'automatic'));setMessage('本部分100%正确，已生成下一 Part 的独立卡片。');},800);
  return()=>clearTimeout(timer);
 },[bundle.main,active,page,update,setMessage]);
 function book(id,action,word,kind){
  if(action==='repeat'){const next=bookAction(bundle,id,action);update(()=>next);setActive(currentAttempt(next.main)?.id);setMessage('已开始本部分新一轮，累计记录保留。');return;}
  update(s=>bookAction(s,id,action,word,kind));
  if(action==='pass')setMessage('已保存本部分，并创建下一 Part 的独立卡片。');
 }
 function quizAction(mode,action,id,kind){update(old=>{
  const s=structuredClone(old),quiz=mode==='daily'?s.daily:s.ordinary,core=mode==='daily'?D:V;if(!quiz)return old;
  let changed=false;if(action==='toggle')changed=core.toggle(quiz,id);if(action==='vote')changed=core.vote(quiz,id,kind);
  if(action==='group'&&Number.isInteger(id)&&id>=0&&id<5){quiz.group=id;changed=true;}
  if(action==='repeat'){
   if(mode==='practice'){s.ordinaryHistory.unshift(structuredClone(quiz));s.ordinaryHistory=s.ordinaryHistory.slice(0,20);s.ordinary=V.restart(quiz,ordinaryBank,false);}
   else{s.dailyHistory.unshift({round:structuredClone(quiz),allowed});s.dailyHistory=s.dailyHistory.slice(0,20);s.daily={...quiz,round:quiz.round+1,launchId:crypto.randomUUID(),opened:{},votes:{},group:0};}changed=true;
  }
  if(action==='next'&&mode==='practice'){s.ordinaryHistory.unshift(structuredClone(quiz));s.ordinaryHistory=s.ordinaryHistory.slice(0,20);s.ordinary=V.restart(quiz,ordinaryBank,true);changed=true;}
  if(mode==='daily'&&changed){s.dailyStats=structuredClone(s.daily.stats);s.dailySerial=s.daily.round;}
  return changed?touch(s):old;
 });}
 async function onImport(e){const f=e.target.files?.[0];if(!f)return;setImporting(true);try{if(f.size>4_000_000)throw Error('文件超过4 MB');const next=importRecord(await f.text(),bundle);adopt(touch(next));setActive(currentAttempt(next.main)?.id);setMessage('已导入主进度和累计记录。');}catch(error){setMessage(error.message);}finally{setImporting(false);e.target.value='';}}
 const selected=bundle.main.attempts.find(a=>a.id===active)||current;
 const syncLabel={loading:'读取记录中',local:'已保存到本机',cloud:'已同步云端',pending:'等待同步',saving:'正在同步',offline:'本机记录 · 同步待重试',conflict:'同步冲突 · 请处理',memory:'暂存中 · 请导出'}[sync];
 return <div className="shell">
  <aside className="sidebar">
   <a href="#/home" className="brand"><span className="brand-mark"><BookOpen size={23}/></span><span>Édito <b>Atelier</b><small>法语词汇学习</small></span></a>
   <div className="nav-label">MON ESPACE<span>学习空间</span></div>
   <nav aria-label="主要导航">{navigation.map(([id,label,Icon])=><a key={id} href={'#/'+id} onClick={e=>{e.preventDefault();go(id);}} className={'nav-item '+(page===id?'active':'')}><Icon size={19}/><span>{label}</span>{page===id&&<i/>}</a>)}</nav>
   <div className="sidebar-book"><span className="book-tag">ÉDITO</span><strong>B1</strong><span>2023 EDITION</span><small>12 单元 · 1110 词</small></div>
   <div className="sidebar-bottom"><button className="nav-item" onClick={()=>go('settings')}><Settings size={18}/>设置与备份</button><button className="user-tile" onClick={()=>setAuth(true)}><span className="avatar">{user?(user.name||user.email||'A')[0].toUpperCase():<GraduationCap size={21}/>}</span><span><strong>{user?.name||'游客学习'}</strong><small>{user?'账号进度同步':'登录后跨设备继续'}</small></span><ChevronRight size={17}/></button></div>
  </aside>
  <main className="main">
   <header className="topbar"><div className="breadcrumb">学习空间<ChevronRight size={14}/><strong>{pageTitles[page]}</strong></div><div className="top-actions"><button className={'sync-chip '+(['offline','conflict','memory'].includes(sync)?'warn':'')} onClick={()=>go('settings')}>{sync==='cloud'?<Cloud size={15}/>:sync==='saving'||sync==='loading'?<LoaderCircle size={15} className="spin"/>:<ShieldCheck size={15}/>}<span>{syncLabel}</span></button><AccountMenu user={user} loading={sync==='loading'&&!user} onLogin={()=>setAuth(true)} onSwitch={switchAccount} onSettings={()=>go('settings')} onLogout={signOut}/></div></header>
   <div className="content">
    {page==='home'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> ÉDITO B1 · 2023</div><h1>Bonjour,<br/><em>à votre rythme.</em></h1><p>从一个词开始，慢慢读懂一个世界。</p><div className="hero-actions"><button className="button primary" onClick={()=>go('textbook')}>继续课本检测<ArrowRight size={18}/></button><button className="text-link" onClick={()=>go('library')}>浏览完整词库<ArrowUpRight size={16}/></button></div></div><div className="hero-art" aria-hidden="true"><div className="art-label">UN MOT À LA FOIS</div><div className="art-note back"><span>LE FRANÇAIS</span><b>une nouvelle<br/>perspective.</b><div>Édito · Niveau B1</div></div><div className="art-note front"><span className="note-dot"/><span>LES MOTS DU QUOTIDIEN</span><b>ensemble</b><i>/ɑ̃sɑ̃bl/</i><div>一起，共同</div><div className="note-line"/></div><span className="art-cross">✦</span></div></section>
     <section className="main-progress-box"><div className="level-circle">B1</div><div className="progress-copy"><div className="split"><strong>我的课本进度</strong><span>{bundle.main.current}<small> / 24 Part</small></span></div><div className="track"><span style={{width:bundle.main.current/24*100+'%'}}/></div><p>{bundle.main.completed?'全书已过关，继续每日复习巩固吧。':`${partName(current?.part)} · ${titles[current?.part]?.zh}`}</p></div><button className="text-link" onClick={()=>go('records')}>查看记录<ChevronRight size={16}/></button></section>
     <div className="section-title"><h2>今天，学一点法语</h2><span>CHOISISSEZ VOTRE PARCOURS</span></div>
     <div className="mode-grid"><button className="mode-card textbook" onClick={()=>go('textbook')}><span className="mode-icon"><BookOpen size={25}/></span><span className="mode-kicker">APPRENDRE · 主进度</span><h3>课本单词检测</h3><p>跟随课本顺序，按主题掌握每个 Part。</p><div><span>{partName(current?.part)} · {current?.ids.length||0} 词</span><ArrowRight size={21}/></div></button><button className="mode-card daily" onClick={()=>go('daily')}><span className="mode-icon"><CalendarDays size={25}/></span><span className="mode-kicker">RÉVISER · 副进度</span><h3>每日单词检测</h3><p>从已过关词汇中抽题，巩固记忆。</p><div><span>{allowed.length>=4?'5 组 · 50 词':'过关 4 个 Part 后开启'}</span><ArrowRight size={21}/></div></button></div>
     <div className="home-bottom"><button className="practice-shortcut" onClick={()=>go('practice')}><span className="neutral-icon"><Shuffle size={22}/></span><span><strong>想换一种练习方式？</strong><small>普通词汇检测 · U1 P1＋P2 · 五组十词</small></span><ChevronRight size={21}/></button><div className="activity"><span><strong>{Object.keys(bundle.main.stats).length}</strong><small>已自评词汇</small></span><span><strong>{totals.good+totals.bad}</strong><small>累计判定</small></span></div></div>
     <footer className="home-footer"><span>Petit à petit, on va loin.</span><span>一点一点，走得更远。</span></footer>
    </>}
    {page==='textbook'&&<><PageIntro english="APPRENDRE" title="课本单词检测" description="每个 Part 一张独立卡片。过关后保存本轮，开启下一部分。"/><div className="study-layout"><div className="study-main">{selected&&<QuizCard key={selected.id} mode="textbook" quiz={selected} stats={bundle.main.stats} groups={T.groups(bank,selected)} action={(...args)=>book(selected.id,...args)} current={selected.part===bundle.main.order[bundle.main.current]&&!bundle.main.completed} totalParts={bundle.main.current}/>}<History main={bundle.main} active={selected?.id} action={book}/></div><ChapterMap main={bundle.main} onCurrent={()=>{setActive(current?.id);window.scrollTo({top:0});}} onBrowse={part=>{setLibraryPart(part);go('library');}}/></div></>}
    {page==='daily'&&<><PageIntro english="RÉVISER" title="每日单词检测" description="只复习已经过关的内容，自评不会推进课本主进度。"/><div className="notice-bar"><CalendarDays size={18}/><span>北京时间 {day()}<b>已过关 {allowed.length} 个 Part</b></span><button className="text-link" onClick={generateDaily}><RotateCcw size={15}/>更新今日词汇</button></div>{bundle.daily?<QuizCard key={bundle.daily.launchId} mode="daily" quiz={bundle.daily} stats={bundle.daily.stats} groups={Array.from({length:5},(_,i)=>({label:bundle.daily.themes[i],ids:bundle.daily.ids.slice(i*10,i*10+10),part:bundle.daily.parts[i]}))} action={(...args)=>quizAction('daily',...args)}/>:<Empty icon={CalendarDays} title="等待课本主进度" text={dailyProblem||D.problem(bank,allowed)||'请更新今日词汇。'}><button className="button primary" onClick={()=>go('textbook')}>继续课本检测<ArrowRight size={17}/></button><button className="button" onClick={()=>input.current.click()}>导入已有进度<Upload size={17}/></button></Empty>}</>}
    {page==='practice'&&<><PageIntro english="S’ENTRAÎNER" title="普通词汇检测" description="第一单元 P1＋P2 混合练习，五组各十词，独立累计，不改变课本过关进度。"/><QuizCard key={'practice-'+bundle.ordinary.round} mode="practice" quiz={bundle.ordinary} stats={bundle.ordinary.stats} groups={Array.from({length:5},(_,i)=>({label:'第 '+(i+1)+' 组',ids:bundle.ordinary.ids.slice(i*10,i*10+10)}))} action={(...args)=>quizAction('practice',...args)}/></>}
    {page==='library'&&<VocabularyLibrary initialPart={libraryPart}/>}
    {page==='records'&&<><PageIntro english="MES PROGRÈS" title="学习记录" description="课本、每日复习与普通检测分别记录。过关记录与每词自评均可追溯。"/><div className="records-stats"><Stat label="课本已过关" value={bundle.main.current} suffix=" / 24 Part"/><Stat label="课本已自评词汇" value={Object.keys(bundle.main.stats).length} suffix=" 词"/><Stat label="课本累计正确" value={totals.good} suffix=" 次"/></div><div className="section-title"><h2>课本过关与检测轮次</h2><button className="text-link" onClick={()=>download(bundle,'edito-atelier-backup.json')}><Download size={16}/>导出完整记录</button></div><div className="record-list">{[...bundle.main.attempts].reverse().map(a=><button key={a.id} onClick={()=>{location.hash='/textbook';setPage('textbook');setActive(a.id);window.scrollTo({top:0});}}><span className={'record-icon '+(a.passReason?'passed':'')} >{a.passReason?<Check size={20}/>:<BookOpen size={20}/>}</span><span><strong>{partName(a.part)} · {titles[a.part]?.zh}</strong><small>第 {a.round} 轮 · 已判 {Object.keys(a.votes).length}/{a.ids.length} 词</small></span><span className={'record-status '+(a.passReason?'passed':'')}>{a.passReason==='automatic'?'100% 自动过关':a.passReason==='manual'?'手动过关':'检测中'}</span><ChevronRight size={17}/></button>)}</div><div className="section-title"><h2>复习与普通检测</h2><span>各保留最近 20 轮</span></div><div className="secondary-records"><div><CalendarDays size={23}/><strong>每日复习</strong><p>{bundle.daily?`本轮 ${D.totals(bundle.daily).done}/50 词已判`:'尚无当前复习轮次'}</p><small>历史 {bundle.dailyHistory.length} 轮 · 副进度</small></div><div><Shuffle size={23}/><strong>普通检测</strong><p>本轮 {V.totals(bundle.ordinary).done}/50 词已判</p><small>历史 {bundle.ordinaryHistory.length} 轮 · 独立练习</small></div></div><RoundRecords daily={bundle.dailyHistory} ordinary={bundle.ordinaryHistory}/></>}
    {page==='settings'&&<><PageIntro english="PRÉFÉRENCES" title="设置与备份" description="把学习记录留在自己手中，在不同设备之间继续。"/><section className="settings-card"><h2><Cloud size={21}/>账号与保存</h2><div className="settings-row"><div><strong>{user?.name||'游客模式'}</strong><p>{user?user.email:'当前学习记录保存在此浏览器。登录后可使用云端同步。'}</p></div><button className="button" onClick={()=>setAuth(true)}>{user?'账号设置':'登录 / 注册'}</button></div><div className="sync-detail"><span className="status-dot"/>{syncLabel}</div>{user&&<div className="settings-buttons"><button className="button" onClick={learning.saveCloud}>重试同步</button><button className="button" onClick={async()=>{try{await learning.pull();}catch(e){setMessage(e.message);}}}>读取云端记录</button><button className="button" onClick={()=>{const guest=learning.guest();if(guest){adopt(touch(guest));setMessage('已导入游客进度到当前账号。');}else setMessage('没有有效游客记录。');}}>导入本机游客进度</button></div>}<p className="subtle-note">同步冲突时，先导出本机完整备份，再读取云端记录。网站与 ChatGPT 插件目前通过进度文件迁移。</p></section><section className="settings-card"><h2><Download size={21}/>进度备份与迁移</h2><p>支持网站完整备份，以及插件导出的 edito-b1-main-progress.json。导入前会校验词条 ID 和判定记录。</p><div className="settings-buttons"><button className="button primary" onClick={()=>download(bundle,'edito-atelier-backup.json')}><Download size={17}/>完整备份</button><button className="button" onClick={()=>download(bundle.main,'edito-b1-main-progress.json')}>导出课本主进度</button><button className="button" disabled={importing} onClick={()=>input.current.click()}><Upload size={17}/>导入进度</button></div></section><section className="settings-card"><h2><Sun size={21}/>界面外观</h2><div className="theme-options">{[['light','浅色',Sun],['dark','深色',Moon],['system','跟随系统',Monitor]].map(([id,label,Icon])=><button className={'button '+(theme===id?'selected':'')} key={id} aria-pressed={theme===id} onClick={()=>setTheme(id)}><Icon size={18}/>{label}</button>)}</div></section><section className="settings-card"><h2><Info size={21}/>关于词库</h2><p>Édito B1 2023 · 12 单元 · 24 个 Part · 1110 条词汇。法语词条与教材页码可回查；中文为辅助释义，音标包含尚待人工校核的自动初稿。</p><a className="text-link" href="https://github.com/Alain-0721/french-vocabulary-test" target="_blank" rel="noreferrer">GitHub 开源代码<ArrowUpRight size={16}/></a></section></>}
   </div>
   <nav className="mobile-nav" aria-label="手机导航">{navigation.filter(x=>x[0]!=='practice').map(([id,label,Icon])=><button key={id} onClick={()=>go(id)} className={page===id?'active':''}><Icon size={20}/><span>{({home:'首页',textbook:'课本',daily:'每日',library:'词库',records:'记录'})[id]}</span></button>)}</nav>
  </main>
  <input ref={input} type="file" accept="application/json,.json" className="hidden" aria-label="导入进度文件" onChange={onImport}/>
  {message&&<div className="toast" role="status"><Info size={18}/><span>{message}</span><button aria-label="关闭提示" onClick={()=>setMessage('')}><X size={17}/></button></div>}
  {auth&&<AccountModal learning={learning} close={closeAccount} switching={switchingAccount}/>}
 </div>;
}

function PageIntro({english,title,description}){return <div className="page-intro"><span className="eyebrow">{english}</span><h1>{title}</h1><p>{description}</p></div>;}
function Stat({label,value,suffix}){return <div className="stat"><span>{label}</span><strong>{value}<small>{suffix}</small></strong></div>;}
function Empty({icon:Icon,title,text,children}){return <section className="empty"><span><Icon size={34}/></span><h2>{title}</h2><p>{text}</p><div>{children}</div></section>;}
function WordRow({id,number,quiz,stats,action}){
 const e=dictionary.get(id),open=!!quiz.opened[id],vote=quiz.votes[id],c=stats[id]||{good:0,bad:0};
 return <article className={'word-row '+(open?'opened':'')} data-word={id}>
  <div className="word-upper"><button className="word-trigger" onClick={()=>action('toggle',id)} aria-expanded={open} aria-controls={'answer-'+(quiz.id||quiz.launchId||'practice-'+quiz.round)+'-'+id}><span className="word-number">{String(number).padStart(2,'0')}</span><strong lang="fr">{e.fr}</strong></button><span className={'ipa '+(!open?'invisible':'')} lang="fr" aria-hidden={!open}>{e.ipa}</span></div>
  <div className="word-lower"><div className="vote-buttons">{['good','bad'].map(kind=><button key={kind} className={'vote '+kind+' '+(vote===kind?'chosen':'')} disabled={!open} aria-label={(kind==='good'?'正确':'错误')+' '+e.fr} aria-pressed={vote===kind} onClick={()=>action('vote',id,kind)}>{kind==='good'?<Check size={17}/>:<X size={17}/>}<span className={!vote?'invisible':''}>{c[kind]}</span></button>)}</div><div id={'answer-'+(quiz.id||quiz.launchId||'practice-'+quiz.round)+'-'+id} className={'answer '+(!open?'invisible':'')} aria-hidden={!open}>{e.zh}</div></div>
 </article>;
}
function QuizCard({mode,quiz,groups,stats,action,current=false}){
 const index=Math.min(quiz.group,groups.length-1),group=groups[index],votes=quiz.ids.map(id=>quiz.votes[id]),done=votes.filter(Boolean).length,good=votes.filter(v=>v==='good').length,bad=done-good;
 const book=mode==='textbook',part=book?quiz.part:group.part;
 return <section className={'quiz-card '+(book&&quiz.passReason?'finished':'')} data-attempt={quiz.id||quiz.launchId||quiz.round}>
  <header className="quiz-header"><div><div className="quiz-meta"><span>{book?partName(part):mode==='daily'?'每日复习 · 副进度':'U1 P1＋P2 · 普通检测'}</span><span>第 {quiz.round} 轮</span>{quiz.passReason&&<span className="passed-tag"><CheckCircle2 size={13}/>已过关</span>}</div><h2>{book?titles[part]?.fr:mode==='daily'?'Les mots à retrouver':'Un peu de pratique'}</h2><p>{book?titles[part]?.zh:mode==='daily'?'每天重逢，熟悉的词汇':'五组十词，自由练习'}</p></div><span className="word-badge">{groups.length} 组 · {quiz.ids.length} 词</span></header>
  <div className="quiz-progress"><div><span>已判 <b>{done}</b> / {quiz.ids.length}</span><span className="quiz-score"><i><Check size={15}/>{good}</i><i><X size={15}/>{bad}</i>{done===quiz.ids.length&&<b>{Math.round(good/quiz.ids.length*100)}%</b>}</span></div><progress value={done} max={quiz.ids.length} aria-label="本轮已判词数"/></div>
  <div className="group-tabs" role="tablist" aria-label="词汇分组">{groups.map((g,i)=><button key={i} type="button" role="tab" aria-selected={i===index} aria-controls={'words-'+(quiz.id||quiz.launchId||mode)} id={'tab-'+(quiz.id||quiz.launchId||mode)+'-'+i} onClick={()=>action('group',i)} className={i===index?'selected':''}>第 {i+1} 组</button>)}</div>
  <div className="theme-heading"><span className="theme-number">{String(index+1).padStart(2,'0')}</span><div><h3 lang="fr">{group.label}</h3>{themeTitles[group.label]&&<p>{themeTitles[group.label]}</p>}{group.part&&<span>{partName(group.part)} · {titles[group.part]?.zh}</span>}</div><span className="group-count">{group.ids.length} 词</span></div>
  <div role="tabpanel" id={'words-'+(quiz.id||quiz.launchId||mode)} aria-labelledby={'tab-'+(quiz.id||quiz.launchId||mode)+'-'+index} className="word-list">{group.ids.map((id,i)=><WordRow key={id} id={id} number={i+1} quiz={quiz} stats={stats} action={action}/>)}</div>
  <div className="quiz-group-footer"><button className="text-link" disabled={index===0} onClick={()=>action('group',index-1)}><ChevronLeft size={16}/>上一组</button><span>{index+1} / {groups.length}</span><button className="text-link" disabled={index===groups.length-1} onClick={()=>action('group',index+1)}>下一组<ChevronRight size={16}/></button></div>
  <div className="quiz-actions"><button className="button" disabled={book&&!current} onClick={()=>action('repeat')}><RotateCcw size={16}/>再测{book?'本部分':'本轮'}</button>{book?<button className="button primary" disabled={!current} onClick={()=>action('pass',null,'manual')}>{quiz.passReason?'本部分已过关':'本部分过关'}<ArrowRight size={17}/></button>:mode==='practice'?<button className="button primary" onClick={()=>action('next')}>换一轮词汇<Shuffle size={17}/></button>:<span className="quiz-tip">本轮自评不会推进课本进度</span>}</div>
  <div className="quiz-note"><Info size={14}/><span>点击法语翻开中文与音标，再选择 ✔／✘。改选会替换本轮判定，累计不会重复增加。</span></div>
 </section>;
}
function History({main,active,action}){
 const previous=[...main.attempts].reverse().filter(a=>a.id!==active);
 if(!previous.length)return null;
 return <section className="history"><div className="section-title"><h2>之前的独立卡片</h2><span>{previous.length} 轮</span></div>{previous.map(a=><details key={a.id}><summary><span><BookOpen size={16}/>{partName(a.part)} · 第 {a.round} 轮</span><span>{a.passReason?'已过关':'已保留'}<ChevronRight size={16}/></span></summary><QuizCard mode="textbook" quiz={a} stats={main.stats} groups={T.groups(bank,a)} action={(...args)=>action(a.id,...args)}/></details>)}</section>;
}
function ChapterMap({main,onCurrent,onBrowse}){return <aside className="chapter-map"><div><h3>课本目录</h3><span>{main.current} / 24 已过关</span></div>{Array.from({length:12},(_,i)=><section key={i}><h4>UNITÉ {String(i+1).padStart(2,'0')}</h4>{parts.filter(p=>p.unit===i+1).map(p=>{const done=main.order.indexOf(p.key)<main.current,current=main.order[main.current]===p.key;return <button key={p.key} className={current?'current':done?'done':''} onClick={()=>current?onCurrent():onBrowse(p.key)}><span>{done?<CheckCircle2 size={16}/>:<span className="part-dot"/>}</span><span><strong>P{p.part} · {titles[p.key]?.zh}</strong><small>{titles[p.key]?.fr}</small></span></button>;})}</section>)}</aside>;}
function VocabularyLibrary({initialPart='all'}){
 const [query,setQuery]=useState(''),[part,setPart]=useState(initialPart),[theme,setTheme]=useState('all'),[limit,setLimit]=useState(40);
 useEffect(()=>{const handler=e=>{setPart(e.detail);setTheme('all');};window.addEventListener('browse-part',handler);return()=>window.removeEventListener('browse-part',handler);},[]);
 useEffect(()=>setLimit(40),[query,part,theme]);
 const themes=[...new Set(bank.filter(e=>part==='all'||T.key(e)===part).map(e=>e.group))];
 const filtered=bank.filter(e=>(part==='all'||T.key(e)===part)&&(theme==='all'||e.group===theme)&&(!query||[e.fr,e.zh].some(v=>v.toLowerCase().includes(query.toLowerCase()))));
 return <><PageIntro english="LE VOCABULAIRE" title="完整词库" description="沿原书顺序整理，保留主题、教材页码与稳定词条编号。"/><div className="library-controls"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索法语或中文…" aria-label="搜索法语或中文"/></label><select aria-label="筛选Part" value={part} onChange={e=>{setPart(e.target.value);setTheme('all');}}><option value="all">全部 24 个 Part</option>{parts.map(p=><option key={p.key} value={p.key}>{partName(p.key)} · {titles[p.key]?.zh}</option>)}</select><select aria-label="筛选主题" value={theme} onChange={e=>setTheme(e.target.value)}><option value="all">全部主题</option>{themes.map(t=><option key={t} value={t}>{t}</option>)}</select></div><div className="library-summary"><span>找到 <b>{filtered.length}</b> 条词汇</span><span>中文与音标为辅助整理，点击详情查看校核状态</span></div><div className="dictionary-list">{filtered.slice(0,limit).map(e=><details className="dictionary-entry" key={e.id}><summary><div><strong lang="fr">{e.fr}</strong><span>{e.ipa}</span></div><div><span>{e.zh}</span><small>{partName(T.key(e))} · p.{e.book_page}</small></div><ChevronRight size={17}/></summary><div className="dictionary-detail"><p><b>主题</b>{e.group} · {themeTitles[e.group]}</p><p><b>词条 ID</b>{e.id}</p><p><b>音标状态</b>{e.ipa_status==='manually_reviewed'?'手动覆盖 / 修正':'自动初稿，待人工校核'}</p><p><b>原书来源</b>{e.original}</p></div></details>)}</div>{!filtered.length&&<Empty icon={Search} title="没有找到匹配词条" text="尝试更短的关键词，或调整 Part 与主题筛选。"/>}{filtered.length>limit&&<div className="load-more"><button className="button" onClick={()=>setLimit(n=>n+40)}>加载更多<Plus size={17}/></button><span>已显示 {Math.min(limit,filtered.length)} / {filtered.length}</span></div>}</>;
}
function RoundRecords({daily,ordinary}){return <div className="round-records">{[...daily.map(h=>({quiz:h.round,label:'每日复习'})),...ordinary.map(quiz=>({quiz,label:'普通检测'}))].map(({quiz,label},i)=><details key={i}><summary><span>{label} · 第 {quiz.round} 轮{quiz.day?' · '+quiz.day:''}</span><span>{Object.values(quiz.votes).filter(v=>v==='good').length} 正确 / {Object.keys(quiz.votes).length} 已判<ChevronRight size={15}/></span></summary><div>{quiz.ids.map(id=><p key={id}><strong lang="fr">{dictionary.get(id)?.fr}</strong><span>{dictionary.get(id)?.zh}</span><i className={quiz.votes[id]||''}>{quiz.votes[id]==='good'?'✔':quiz.votes[id]==='bad'?'✘':'未判'}</i></p>)}</div></details>)}</div>;}

function AccountModal({learning,close,switching=false}){
 const modal=useRef();
 const {user,settings,authCallback,setAuthCallback,setMessage}=learning;
 const callbackMode=authCallback?.type==='recovery'?'reset':authCallback?.type==='invite'?'reset':null;
 const showAccount=!!user&&!callbackMode&&!switching;
 const [mode,setMode]=useState(callbackMode||'login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const old=document.activeElement;modal.current?.querySelector('input,button')?.focus();const fn=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...modal.current.querySelectorAll('input,button')].filter(n=>!n.disabled);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',fn);return()=>{window.removeEventListener('keydown',fn);old?.focus();};},[close]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{
  if(mode==='reset'){if(authCallback?.type==='invite')await acceptInvite(authCallback.token,password);else await updateUser({password});setAuthCallback(null);setMessage('密码已更新。');close();}
  else if(mode==='forgot'){await requestPasswordRecovery(email);setError('如果该邮箱已注册，你将收到密码恢复邮件。');}
  else if(mode==='signup'){const u=await signup(email,password,{full_name:name});if(u.confirmedAt){setMessage('注册成功，可以开始云端同步。');close();}else setError('请查收确认邮件，验证后登录。');}
  else{await login(email,password);setMessage('已登录，账号记录与游客记录分别保存。');close();}
 }catch(err){setError(err.status===401?'邮箱或密码不正确，请重新输入。':err.message||'操作失败，请稍后重试。');}finally{setBusy(false);setPassword('');}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section ref={modal} className="account-modal" role="dialog" aria-modal="true" aria-labelledby="account-title"><button className="modal-close" aria-label="关闭账号窗口" onClick={close}><X size={21}/></button><span className="brand-mark"><BookOpen size={24}/></span><h2 id="account-title">{showAccount?'我的学习账号':({login:switching?'切换学习账号':'继续你的法语之旅',signup:'创建学习账号',forgot:'找回密码',reset:'设置新密码'})[mode]}</h2>{showAccount?<><p>{user.name||'学习者'}<br/>{user.email}</p><div className="modal-note"><Cloud size={20}/>登录后的记录按账号保存，手机和电脑可继续同一进度。</div><button className="button full" onClick={async()=>{await logout();setMessage('已退出，恢复游客学习记录。');close();}}><LogOut size={17}/>退出登录</button></>:settings===false?<><p>账号服务暂时不可用。可以继续游客学习，记录保存在本机，并支持导出备份。</p><button className="button primary full" onClick={close}>继续游客学习</button></>:<><p>{mode==='login'?(switching?'登录另一个账号，验证成功后切换；取消可保留当前账号。':'登录后，让手机和电脑共享学习进度。'):mode==='signup'?'现有游客记录仍会保留，登录后可手动导入。':'通过邮件验证后恢复访问。'}</p><form onSubmit={submit}>{mode==='signup'&&<label>昵称<input required value={name} maxLength={40} autoComplete="nickname" onChange={e=>setName(e.target.value)} placeholder="你的名字"/></label>}{mode!=='reset'&&<label>邮箱<input type="email" required value={email} autoComplete="email" onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoFocus/></label>}{mode!=='forgot'&&<label>密码<input type="password" required minLength={mode==='login'?1:8} value={password} autoComplete={mode==='login'?'current-password':'new-password'} onChange={e=>setPassword(e.target.value)} placeholder={mode==='login'?'输入密码':'至少 8 位'}/></label>}{mode==='login'&&<div className="account-remember-note"><ShieldCheck size={16}/><span>默认保持登录。下次打开自动恢复有效会话，无需重新输入密码。</span></div>}{error&&<p className="form-message" role="status">{error}</p>}<button className="button primary full" disabled={busy||settings===null} type="submit">{busy?<LoaderCircle size={18} className="spin"/>:null}{({login:'登录',signup:'注册',forgot:'发送恢复邮件',reset:'保存新密码'})[mode]}</button></form>{mode==='login'&&<div className="auth-links">{settings?.disableSignup===false&&<button onClick={()=>{setMode('signup');setError('');}}>创建账号</button>}<button onClick={()=>{setMode('forgot');setError('');}}>忘记密码？</button></div>}{mode!=='login'&&mode!=='reset'&&<button className="text-link center" onClick={()=>{setMode('login');setError('');}}>返回登录</button>}</>}</section></div>;
}

createRoot(document.getElementById('root')).render(<App/>);
