import React,{useState,useEffect} from 'react';
import {BookOpen,CalendarDays,Library,ChartNoAxesCombined,ArrowRight,ArrowUpRight,ChevronRight,Shuffle,Info,Download,Upload,Cloud,Sun,Moon,Monitor,RotateCcw,Search,Plus,GraduationCap} from 'lucide-react';
import * as Study from './preview-study.js';
import {day,eligible,practiceBank,reviewGroups} from './preview-review.js';
import {Settings,Records,WordRow} from './study-preview-ui.jsx';
import {PwaInstall} from './pwa-ui.jsx';

export const PRODUCTION='https://franmotest.netlify.app';
const short=p=>p?.replace(/^U(\d+)P(\d+)$/,'U$1 · P$2')||'';
export function Home({books=[],book,state,go,titleFor,production=false}){
  const a=state&&Study.active(state),passed=state?Study.masteredCount(state):0,total=state?.order.length||0,stats=Object.values(state?.stats||{}),ratings=stats.reduce((n,c)=>n+c.good+c.bad,0),first=book.bank?.[0];
  return <div className="np-home"><section className="np-hero"><div><span className="dp-eyebrow">{book.name.toUpperCase()} · {book.edition}</span><h1>Bonjour,<br/><em>à votre rythme.</em></h1><p>从一个词开始，慢慢读懂一个世界。</p><div className="vi-actions"><button className="dp-button primary" onClick={()=>go('study')}>继续课本过关<ArrowRight size={16}/></button><button className="dp-text-button" onClick={()=>go('library')}>浏览完整词库<ArrowUpRight size={15}/></button></div></div><div className="np-hero-art" aria-hidden="true"><span>UN MOT À LA FOIS</span><div className="np-art-back"><small>LE FRANÇAIS</small><strong>une nouvelle<br/>perspective.</strong><span>{book.name} · {book.level}</span></div><div className="np-art-front"><small>LES MOTS DU QUOTIDIEN</small><strong lang="fr">{first?.fr||'ensemble'}</strong><i>{first?.ipa||'/ɑ̃sɑ̃bl/'}</i><span>{first?.zh||'一起，共同'}</span></div></div></section>
    <div className="np-section-heading"><h2>今天，学一点法语</h2><button className="dp-text-button" onClick={()=>go('books')}><Library size={15}/>我的课本<ChevronRight size={14}/></button></div><div className="np-modes"><button onClick={()=>go('study')}><span className="np-mode-icon"><BookOpen size={24}/></span><small>APPRENDRE · 主进度</small><h2>课本过关</h2><p>按主题翻词自测，任选 Part，已过关也可重测。</p><div><span>{a?`${short(a.part)} · ${a.ids.length} 词`:book.name}</span><ArrowRight size={19}/></div></button><button onClick={()=>go('daily')}><span className="np-mode-icon"><CalendarDays size={24}/></span><small>RÉVISER · 副进度</small><h2>每日检测</h2><p>只从本书已过关的主题抽题，不推进课本进度。</p><div><span>{passed>=4?'5 组 · 各 10 词，按主题词数生成':'过关 4 个 Part 后开启'}</span><ArrowRight size={19}/></div></button></div>
    <div className="np-home-bottom"><button className="np-shortcut" onClick={()=>go('practice')}><Shuffle size={23}/><span><strong>想换一种练习方式？</strong><small>普通词汇检测 · 第一单元 P1＋P2 · 五组十词</small></span><ChevronRight size={19}/></button></div>
    <section className="np-progress"><span className="np-level">{book.level}</span><div><div><strong>我的课本进度</strong><span>{passed}<small> / {total} Part</small></span></div><div className="dp-track"><span style={{width:total?passed/total*100+'%':'0%'}}/></div><p>{a?`${short(a.part)} · ${titleFor(book,a.part)?.zh||titleFor(book,a.part)?.fr}`:'导入词库后开始学习'}{state?.completed?' · 全书已过关，可继续重测巩固':''}</p></div><button className="dp-text-button" onClick={()=>go('records')}>查看记录<ChevronRight size={15}/></button></section>
    <div className="np-activity"><span><strong>{stats.length}</strong><small>已自评词汇</small></span><span><strong>{ratings}</strong><small>累计判定</small></span></div>
    <button className="np-books-entry" aria-label="打开我的课本" onClick={()=>go('books')}><span className="np-books-entry-copy"><span className="dp-eyebrow"><Library size={15}/>MA BIBLIOTHÈQUE</span><strong>我的课本</strong><span>选择课本，继续你的词汇旅程。<br/>添加自己的课本，让每一本都有独立进度。</span><span className="np-books-entry-meta"><span>{books.length} 本课本</span><i/><span>{books.filter(b=>b.bank).length} 本可检测</span><span className="np-books-entry-action">进入我的课本<ArrowRight size={16}/></span></span></span><span className="np-books-entry-art" aria-hidden="true">{books.filter(b=>b.bank).slice(0,3).map((b,i)=><span key={b.id} className={`np-mini-cover cover-${i}`}><span>{b.series||b.name}</span><strong>{b.level}</strong><small>VOCABULAIRE</small></span>)}</span><ArrowUpRight className="np-books-entry-arrow" size={23}/></button>
    {production&&<PwaInstall compact/>}
    <section className="np-tutorial-entry"><Info size={23}/><div><h2>第一次使用 Atelier？</h2><p>了解检测、重测与统计，或把自己的课本 PDF 整理成词库。</p></div><div><button className="dp-button" onClick={()=>go('about')}>网站介绍与使用教程<ArrowRight size={14}/></button><button className="dp-text-button" onClick={()=>go('guide')}>词库生成与导入教程<ArrowUpRight size={14}/></button></div></section><footer className="dp-footer"><span>Petit à petit, on va loin.</span><span>一点一点，走得更远。</span></footer></div>;
}

export function SettingsAndBackup({book,settings,onChange,theme,onTheme,onFullBackup,onMainBackup,onImport,go,production=false,learning,onAccount,onGuest}){
  return <div className="np-settings">{production&&<PwaInstall/>}<section className="vi-panel"><h2><Cloud size={20}/>账号与保存</h2>{production?<><div className="np-setting-row"><div><strong>{learning.user?.name||learning.offlineAccount?.name||'游客模式'}</strong><p>{learning.user?learning.user.email:learning.offlineAccount?'正在使用原账号的本机记录；联网验证登录后再同步。':'学习记录保存在当前浏览器，登录后可同步到其他设备。'}</p></div><button className="dp-button" onClick={onAccount}>{learning.user?'账号设置':learning.offlineAccount?'联网登录':'登录 / 注册'}</button></div><p role="status">{({loading:'正在恢复记录',local:'已保存到本机',memory:'浏览器保存受限，请及时导出备份',pending:'等待同步',saving:'正在同步',cloud:'已同步到云端',offline:'云端暂不可用，记录保存在本机','offline-account':'本机账号记录，联网后验证登录并同步',conflict:'另一台设备已更新，请先导出本机备份，再读取云端'})[learning.sync]}</p>{learning.user&&<div className="vi-actions"><button className="dp-button" onClick={learning.saveCloud}>重试同步</button><button className="dp-button" onClick={async()=>{if(!confirm('读取云端记录将替换当前本机记录。建议先导出完整备份，是否继续？'))return;try{await learning.pull();}catch(e){learning.setMessage(e.message);}}}>读取云端记录</button><button className="dp-button" onClick={onGuest}>导入本机游客进度</button></div>}<p className="vi-muted">游客和各账号分别保存。同步冲突时请先备份；更换网址后，旧网址的游客记录需要通过备份迁移。</p></>:<><div className="np-setting-row"><div><strong>本地预览模式</strong><p>当前检测进度暂存在本次页面中，刷新前可导出备份。正式站保留游客本机保存、登录及云端同步。</p></div><a className="dp-button" href={PRODUCTION+'/#/settings'} target="_blank" rel="noreferrer">正式站账号与同步<ArrowUpRight size={15}/></a></div><p className="vi-muted">预览导入与设置只在本地生效。</p></>}</section>
    <section className="vi-panel"><h2><Download size={20}/>进度备份与迁移</h2><p>完整备份包含各本课本、检测轮次、累计对错、复习与布局设置。也支持导入原 Édito B1 网站备份或插件主进度，继续课本检测。</p><div className="vi-actions"><button className="dp-button primary" onClick={onFullBackup}><Download size={16}/>完整备份</button><button className="dp-button" onClick={onMainBackup} disabled={!book.bank}>导出本书主进度</button><button className="dp-button" onClick={onImport}><Upload size={16}/>导入进度</button></div><p className="vi-muted">{production?'备份包含各本课本的进度和词库；原网站完整备份可迁移 Édito B1 主进度、每日检测和普通练习。恢复前检查并显示导入范围。':'备份可迁移本次预览记录；原网站文件只迁移 Édito B1 主进度。恢复前会先检查并显示导入范围。'}</p></section>
    <section className="vi-panel"><h2><Sun size={20}/>界面外观</h2><div className="np-theme-options">{[['light','浅色',Sun],['dark','深色',Moon],['system','跟随系统',Monitor]].map(([id,label,Icon])=><button key={id} className={`dp-button ${theme===id?'selected':''}`} aria-pressed={theme===id} onClick={()=>onTheme(id)}><Icon size={18}/>{label}</button>)}</div></section>
    <Settings production={production} settings={settings} onChange={onChange}/>
    <section className="vi-panel"><h2><Info size={20}/>网站介绍与使用教程</h2><p>从选择课本、翻词自评，到重测统计、每日复习与备份迁移。</p><div className="vi-actions"><button className="dp-button" onClick={()=>go('about')}>网站介绍与使用教程<ArrowRight size={15}/></button><button className="dp-button" onClick={()=>go('guide')}>词库生成与导入教程<ArrowRight size={15}/></button></div></section>
    <section className="vi-panel"><h2><BookOpen size={20}/>关于词库</h2><p>{book.name} · {book.edition} · {book.bank?.length||0} 条词汇。保留原书主题、教材页码与音标校核状态；中文释义和音标供学习辅助。</p><div className="vi-actions"><button className="dp-text-button" onClick={()=>go('books')}>管理我的课本<ArrowRight size={15}/></button><a className="dp-text-button" href="https://github.com/Alain-0721/french-vocabulary-test" target="_blank" rel="noreferrer">GitHub 开源代码<ArrowUpRight size={15}/></a></div></section></div>;
}

export function LibraryStatistics({book,state,view,go,titleFor,themeFor,secondary,production=false}){
  const [query,setQuery]=useState(''),[part,setPart]=useState('all'),[theme,setTheme]=useState('all'),[limit,setLimit]=useState(40);
  useEffect(()=>setLimit(40),[query,part,theme]);
  const themes=[...new Set(book.bank.filter(e=>part==='all'||Study.key(e)===part).map(e=>e.group))],normalized=query.toLocaleLowerCase();
  const found=book.bank.filter(e=>(part==='all'||Study.key(e)===part)&&(theme==='all'||e.group===theme)&&[e.fr,e.zh].some(s=>s.toLocaleLowerCase().includes(normalized)));
  return <><div className="np-library-tabs" role="tablist" aria-label="词库与统计"><button role="tab" aria-selected={view!=='records'} onClick={()=>go('library')}><Library size={16}/>完整词库</button><button role="tab" aria-selected={view==='records'} onClick={()=>go('records')}><ChartNoAxesCombined size={16}/>学习记录</button></div>{view==='records'?<><Records production={production} book={book} state={state} titleFor={titleFor}/><ReviewRecords book={book} secondary={secondary}/></>:<>
    <div className="np-library-controls"><label className="dp-search"><Search size={17}/><input aria-label="搜索法语或中文" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索法语或中文…"/></label><select aria-label="筛选 Part" value={part} onChange={e=>{setPart(e.target.value);setTheme('all');}}><option value="all">全部 {state.order.length} 个 Part</option>{Study.parts(book.bank).map(p=><option key={p.key} value={p.key}>{short(p.key)} · {titleFor(book,p.key)?.zh||titleFor(book,p.key)?.fr}</option>)}</select><select aria-label="筛选主题" value={theme} onChange={e=>setTheme(e.target.value)}><option value="all">全部主题</option>{themes.map(t=><option key={t} value={t}>{t}</option>)}</select></div><div className="np-library-summary"><span>找到 <b>{found.length}</b> 条词汇</span><span>点击详情查看原书来源及音标状态</span></div>
    <div className="np-dictionary">{found.slice(0,limit).map(e=><details key={e.id}><summary><div><strong lang="fr">{e.fr}</strong><span>{e.ipa||'未提供音标'}</span></div><div><span>{e.zh}</span><small>{short(Study.key(e))} · p.{e.book_page||'未标注'}</small></div><ChevronRight size={16}/></summary><div className="np-dictionary-details"><p><b>主题</b>{e.group} · {themeFor(book,e)}</p><p><b>词条 ID</b>{e.id}</p><p><b>音标状态</b>{e.ipa_status==='manually_reviewed'?'来源标记为已校对':e.ipa_status?'待校核 · '+e.ipa_status:'未提供校核状态'}</p><p><b>原书来源</b>{e.original||e.lemma_in_book||e.fr}</p></div></details>)}</div>{!found.length&&<section className="dp-empty compact"><Search size={24}/><h2>没有找到匹配词条</h2><p>尝试其他关键词，或调整 Part 与主题。</p></section>}{found.length>limit&&<div className="np-load-more"><button className="dp-button" onClick={()=>setLimit(n=>n+40)}>加载更多<Plus size={15}/></button><span>已显示 {Math.min(limit,found.length)} / {found.length}</span></div>}</>}</>;
}

export function ReviewQuiz({book,quiz,mode,settings,changeSettings,act,themeFor}){
  const groups=reviewGroups(quiz,mode),group=groups[quiz.group],source=mode==='daily'?book.bank:practiceBank(book),dictionary=new Map(source.map(e=>[e.id,e])),attempt={...quiz,id:mode==='daily'?quiz.launchId:`practice-${quiz.round}`},first=dictionary.get(group.ids[0]);
  return <section className={`dp-quiz study-quiz layout-${settings.layout}`}><header className="quiz-heading"><div><div className="quiz-meta"><span>{book.name}</span><span>{mode==='daily'?'每日检测 · '+quiz.day:'普通词汇检测 · U1 P1＋P2'}</span><span>第 {quiz.round} 轮</span></div><h2>{mode==='daily'?'Aujourd’hui, on révise.':'Un peu de pratique.'}</h2><p>{mode==='daily'?'只取已过关部分，每组来自同一主题。':'第一单元混合练习，独立累计，不改变课本过关。'}</p></div><span className="quiz-word-count">5 组 · 50 词</span></header><div className="study-tools"><span>本轮已判 {Object.keys(quiz.votes).length} / 50 词</span><label>卡片布局<select aria-label="切换卡片布局" value={settings.layout} onChange={e=>changeSettings({layout:e.target.value})}><option value="classic">对错在左 · 翻译在右</option><option value="right">翻译在左 · 对错在右</option></select></label></div><div className="dp-group-tabs" role="tablist" aria-label="主题分组">{groups.map((g,i)=><button key={i} role="tab" aria-selected={quiz.group===i} className={quiz.group===i?'active':''} onClick={()=>act('group',i,null,attempt.id)}>第 {i+1} 组</button>)}</div><div className="dp-theme"><span>{String(quiz.group+1).padStart(2,'0')}</span><div><h3 lang="fr">{group.label}</h3><p>{mode==='daily'?`${short(group.part)} · ${themeFor(book,first)}`:'P1＋P2 混合词汇'}</p></div><small>10 词</small></div><div className="dp-word-list">{group.ids.map((id,i)=><WordRow key={id} entry={dictionary.get(id)} index={i} attempt={attempt} stats={quiz.stats[id]} act={act}/>)}</div><div className="dp-quiz-footer"><span>副进度独立 · 点击整行翻词</span><span>{quiz.group+1} / 5 组</span></div><div className="dp-quiz-actions"><button className="dp-button" onClick={()=>act('repeat',null,null,attempt.id)}><RotateCcw size={15}/>重新测评本轮</button>{mode==='practice'&&<button className="dp-button primary" onClick={()=>act('next',null,null,attempt.id)}>下一轮词汇<ArrowRight size={15}/></button>}</div></section>;
}

export function DailyIntro({book,state,onGenerate}){
  return <div className="np-daily-notice"><CalendarDays size={18}/><span>北京时间 {day()}<b>{book.name} · 已过关 {eligible(state).length} 个 Part</b></span><button className="dp-text-button" onClick={onGenerate}><RotateCcw size={15}/>更新今日词汇</button></div>;
}
function ReviewRecords({book,secondary}){
  return <section className="np-review-records"><h2>每日检测与普通练习</h2><div className="np-review-summary">{[['daily','每日检测',CalendarDays],['practice','普通检测',Shuffle]].map(([mode,label,Icon])=>{const q=secondary?.[mode],hist=secondary?.[mode+'History']||[],total=Object.values(q?.stats||{}).reduce((n,c)=>n+c.good+c.bad,0);return <div key={mode}><Icon size={22}/><strong>{label}</strong><p>本轮已判 {Object.keys(q?.votes||{}).length} / {q?50:0} 词</p><small>累计 {total} 次 · 历史 {hist.length} 轮 · 副进度独立</small></div>;})}</div>{['daily','practice'].map(mode=>(secondary?.[mode+'History']||[]).map((h,i)=>{const q=mode==='daily'?h.round:h,source=mode==='daily'?book.bank:practiceBank(book),map=new Map(source.map(e=>[e.id,e]));return <details key={mode+i}><summary>{mode==='daily'?'每日检测':'普通检测'} · 第 {q.round} 轮 · {Object.keys(q.votes).length}/50 词已判</summary>{q.ids.map(id=><p key={id}><strong>{map.get(id)?.fr}</strong><span>{map.get(id)?.zh}</span><small>{q.votes[id]==='good'?'✔':q.votes[id]==='bad'?'✘':'未判'}</small></p>)}</details>;}))}</section>;
}
