import {readFileSync,mkdirSync,writeFileSync,copyFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import './generate.mjs';

const project=fileURLToPath(new URL('../',import.meta.url)),root=resolve(project,'..');
const config=JSON.parse(readFileSync(join(root,'.netlify/android-tools/config.json'),'utf8'));
const manifest=JSON.parse(readFileSync(join(project,'app-config.json'),'utf8'));
const env={...process.env,JAVA_HOME:config.jdkPath,ANDROID_HOME:config.androidSdkPath,ANDROID_SDK_ROOT:config.androidSdkPath,GRADLE_USER_HOME:join(root,'.netlify/android-tools/gradle-cache')};
if(process.platform!=='win32')throw Error('This local build runner is for Windows. Use Gradle and apksigner directly on other platforms.');
execFileSync('cmd.exe',['/d','/s','/c','gradlew.bat assembleRelease assembleDebug lintRelease --no-daemon --console=plain'],{cwd:project,env,stdio:'inherit'});
const tools=join(config.androidSdkPath,'build-tools/36.1.0'),output=join(root,'.netlify/releases/android-'+manifest.appVersion);mkdirSync(output,{recursive:true});
const apkName='Franmotest-'+manifest.appVersion+'-Android.apk',apk=join(output,apkName);
execFileSync(join(tools,'zipalign.exe'),['-P','16','-f','4',join(project,'app/build/outputs/apk/release/app-release-unsigned.apk'),apk],{env,stdio:'inherit'});
const java=join(config.jdkPath,'bin/java.exe'),signer=join(tools,'lib/apksigner.jar');
const {password}=JSON.parse(readFileSync(join(root,'.netlify/android-signing/password.json'),'utf8'));
const signingEnv={...env,FRANMOTEST_SIGNING_PASSWORD:password};
execFileSync(java,['-jar',signer,'sign','--ks',resolve(project,manifest.signingKey.path),'--ks-key-alias',manifest.signingKey.alias,'--ks-pass','env:FRANMOTEST_SIGNING_PASSWORD','--key-pass','env:FRANMOTEST_SIGNING_PASSWORD',apk],{env:signingEnv,stdio:'inherit'});
const verification=execFileSync(java,['-jar',signer,'verify','--verbose','--print-certs',apk],{env,encoding:'utf8'});
const fingerprint=manifest.fingerprints[0].value.replaceAll(':','').toLowerCase();
if(!verification.toLowerCase().includes(fingerprint))throw Error('APK signing certificate differs from website association.');
execFileSync(join(tools,'zipalign.exe'),['-c','-P','16','4',apk],{env,stdio:'inherit'});
const info=execFileSync(join(tools,'aapt.exe'),['dump','badging',apk],{env,encoding:'utf8'});
if(!info.includes("name='"+manifest.packageId+"'")||!info.includes("versionName='"+manifest.appVersion+"'")||!info.includes("versionCode='"+manifest.appVersionCode+"'"))throw Error('APK package or version differs from manifest.');
writeFileSync(join(output,'apk-verification.txt'),verification+'\n'+info);
const hash=createHash('sha256').update(readFileSync(apk)).digest('hex');
writeFileSync(join(output,'Franmotest-Android-SHA256SUMS.txt'),hash+'  '+apkName+'\n');
copyFileSync(join(project,'INSTALL.md'),join(output,'Franmotest-Android-Installation.md'));
console.log(JSON.stringify({apk,package:manifest.packageId,version:manifest.appVersion,sha256:hash,signatureVerified:true}));
