import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {JSDOM} from 'jsdom';
const dir=await mkdtemp(join(tmpdir(),'edito-test-'));
let passed=0;
function check(name,fn){fn();passed++;console.log('✓ '+name);}
try{
 await build({entryPoints:['src/engine.js'],bundle:true,platform:'node',format:'esm',outfile:join(dir,'engine.mjs'),logLevel:'silent'});
 const {bank,ordinaryBank,T,D,V,fresh,currentAttempt,bookAction,makeDaily,restoreBundle,importRecord}=await import(pathToFileURL(join(dir,'engine.mjs')));
 let s=fresh();const first=currentAttempt(s.main),id=first.ids[0];
 check('1110 stable entries and 24 Parts',()=>{assert.equal(bank.length,1110);assert.equal(new Set(bank.map(e=>e.id)).size,1110);assert.equal(s.main.order.length,24);});
 check('Fresh users start U1P1 without mastered Parts',()=>{assert.equal(first.part,'U1P1');assert.equal(s.main.current,0);assert.equal(s.daily,null);});
 check('Hidden words cannot be rated',()=>assert.equal(bookAction(s,first.id,'vote',id,'good'),s));
 s=bookAction(s,first.id,'toggle',id);s=bookAction(s,first.id,'vote',id,'good');
 check('Duplicate votes do not double count',()=>assert.equal(bookAction(s,first.id,'vote',id,'good'),s));
 s=bookAction(s,first.id,'vote',id,'bad');
 check('Changed votes replace cumulative totals',()=>assert.deepEqual(s.main.stats[id],{good:0,bad:1}));
 s=bookAction(s,first.id,'pass',null,'manual');const second=currentAttempt(s.main);
 check('Manual pass creates a separate card preserving the old one',()=>{assert.notEqual(second.id,first.id);assert.equal(second.part,'U1P2');assert.equal(s.main.attempts[0].votes[id],'bad');assert.equal(s.main.attempts[0].passReason,'manual');assert.deepEqual(second.votes,{});});
 check('Every textbook group contains a complete single theme',()=>{for(const g of T.groups(bank,second)){assert.equal(new Set(g.ids.map(id=>bank.find(e=>e.id===id).group)).size,1);assert.equal(g.ids.length,bank.filter(e=>T.key(e)===second.part&&e.group===g.label).length);}});
 let auto=fresh(),a=currentAttempt(auto.main);
 for(const word of a.ids){auto=bookAction(auto,a.id,'toggle',word);auto=bookAction(auto,a.id,'vote',word,'good');}
 auto=bookAction(auto,a.id,'pass',null,'automatic');
 check('100 percent automatically passes with new card',()=>{assert.equal(auto.main.current,1);assert.equal(auto.main.attempts[0].passReason,'automatic');assert.notEqual(currentAttempt(auto.main).id,a.id);});
 auto=bookAction(auto,a.id,'vote',a.ids[0],'bad');
 check('Correcting automatic history restores the earlier main Part',()=>{assert.equal(auto.main.current,0);assert.equal(currentAttempt(auto.main).id,a.id);assert.equal(auto.main.attempts.length,2);assert.ok(restoreBundle(auto));});
 check('Daily requires four passed Parts',()=>assert.ok(makeDaily(fresh()).problem));
 let fixture=fresh();for(let i=0;i<4;i++)fixture=bookAction(fixture,currentAttempt(fixture.main).id,'pass',null,'manual');
 const mainJSON=JSON.stringify(fixture.main);fixture=makeDaily(fixture).state;
 check('Daily samples 5 single-theme groups from mastered Parts',()=>{assert.ok(D.validRound(fixture.daily,bank,D.eligible(fixture.main,bank)));assert.deepEqual(fixture.daily.parts.slice(0,4),['U2P2','U2P2','U2P1','U1P2']);assert.equal(fixture.daily.parts[4],'U1P1');assert.equal(new Set(fixture.daily.ids).size,50);});
 const d=fixture.daily.ids[0];D.toggle(fixture.daily,d);D.vote(fixture.daily,d,'good');fixture.dailyStats=structuredClone(fixture.daily.stats);fixture.dailySerial=fixture.daily.round;
 fixture=makeDaily(fixture).state;
 check('Daily refresh preserves scores without advancing main',()=>{assert.equal(JSON.stringify(fixture.main),mainJSON);assert.equal(fixture.daily.stats[d].good,1);assert.equal(fixture.dailyHistory.length,1);assert.equal(fixture.daily.round,2);});
 fixture=bookAction(fixture,currentAttempt(fixture.main).id,'pass',null,'manual');
 check('Changing main archives obsolete daily sample and preserves totals',()=>{assert.equal(fixture.daily,null);assert.equal(fixture.dailyHistory.length,2);assert.equal(fixture.dailyStats[d].good,1);assert.ok(restoreBundle(fixture));});
 fixture=makeDaily(fixture).state;
 check('Full backup round trips',()=>assert.ok(restoreBundle(JSON.stringify(fixture))));
 check('Plugin main-progress imports without fake secondary progress',()=>{const imported=importRecord(JSON.stringify(fixture.main),fresh());assert.equal(imported.main.current,5);assert.equal(imported.daily,null);assert.deepEqual(imported.dailyStats,{});});
 check('Malformed imports and unknown IDs are rejected',()=>{const invalid=structuredClone(fixture);invalid.main.stats.unknown={good:1,bad:0};assert.equal(restoreBundle(invalid),null);assert.throws(()=>importRecord({mode:'textbook'},fresh()));});
 await build({entryPoints:['netlify/functions/progress.mts'],bundle:true,format:'esm',platform:'node',outfile:join(dir,'api.mjs'),plugins:[{name:'server-test',setup(b){b.onResolve({filter:/^@netlify\/(identity|blobs)$/},args=>({path:args.path,namespace:'server-mock'}));b.onLoad({filter:/.*/,namespace:'server-mock'},args=>({contents:args.path.endsWith('identity')?`export class AuthError extends Error{};export const getUser=async()=>globalThis.testUser;export function verifyRequestOrigin(req){if(req.headers.get('Origin')!==new URL(req.url).origin)throw new AuthError('Origin');}`:`const records=new Map();let seq=0;function store(prefix){return {getWithMetadata:async key=>records.get(prefix+key)||null,setJSON:async(key,data,opts)=>{key=prefix+key;const old=records.get(key);if(opts.onlyIfNew&&old||opts.onlyIfMatch&&old?.etag!==opts.onlyIfMatch)return {modified:false};const etag=String(++seq);records.set(key,{data,etag});return {modified:true,etag};}}};export const getStore=()=>store('production:'),getDeployStore=()=>store('preview:');`,loader:'js'}));}}],logLevel:'silent'});
 const api=(await import(pathToFileURL(join(dir,'api.mjs')))).default;
 const request=(method='GET',data,etag=null,origin='https://example.test')=>new Request('https://example.test/api/progress',{method,headers:{Origin:origin,'Content-Type':'application/json'},...(method==='PUT'?{body:JSON.stringify({data,etag})}:{})});
 const context={deploy:{context:'production'}};
 globalThis.testUser=null;
 assert.equal((await api(request(),context)).status,401);console.log('✓ Cloud API rejects anonymous access');passed++;
 globalThis.testUser={id:'test-user-a'};
 let response=await api(request('PUT',fresh()),context);assert.equal(response.status,200);const token=(await response.json()).etag;
 assert.equal((await api(request('PUT',fresh()),context)).status,409);console.log('✓ Atomic cloud writes reject stale or missing ETags');passed++;
 response=await api(request('PUT',fresh(),token),context);assert.equal(response.status,200);
 assert.equal((await api(request('PUT',{mode:'invalid'},token),context)).status,400);
 assert.equal((await api(request('PUT',fresh(),token,'https://other.test'),context)).status,403);console.log('✓ Cloud API validates data and request origin');passed++;
 globalThis.testUser={id:'test-user-b'};
 assert.equal((await (await api(request(),context)).json()).data,null);
 globalThis.testUser={id:'test-user-a'};
 assert.equal((await (await api(request(),{deploy:{context:'deploy-preview'}})).json()).data,null);console.log('✓ Accounts and preview deployments have isolated progress');passed++;
 delete globalThis.testUser;
 const ordinary=V.create(ordinaryBank);
 check('Ordinary mode is 50 words and separate from main',()=>{assert.equal(ordinary.ids.length,50);assert.equal(new Set(ordinary.ids).size,50);assert.equal(T.create(bank).current,0);});
 const dom=new JSDOM('<!DOCTYPE html><div id="root"></div>',{url:'https://example.test/#/home',pretendToBeVisual:true,runScripts:'dangerously'});
 dom.window.structuredClone=structuredClone;dom.window.scrollTo=()=>{};
 const result=await build({entryPoints:['src/main.jsx'],bundle:true,write:false,format:'iife',platform:'browser',loader:{'.css':'empty'},plugins:[{name:'auth-test',setup(b){b.onResolve({filter:/^@netlify\/identity$/},()=>({path:'identity',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const getUser=async()=>null,getSettings=async()=>({disableSignup:false}),handleAuthCallback=async()=>null,refreshSession=async()=>null,onAuthChange=()=>()=>{};export const login=async()=>{},signup=async()=>({}),logout=async()=>{},requestPasswordRecovery=async()=>{},updateUser=async()=>{},acceptInvite=async()=>{};',loader:'js'}));}}],logLevel:'silent'});
 dom.window.eval(result.outputFiles[0].text);await new Promise(r=>setTimeout(r,80));
 const doc=dom.window.document;
 check('Home renders real fresh progress',()=>{assert.match(doc.body.textContent,/Bonjour/);assert.match(doc.body.textContent,/0 \/ 24 Part/);});
 const click=async el=>{assert.ok(el);el.click();await new Promise(r=>setTimeout(r,45));};
 await click([...doc.querySelectorAll('button')].find(e=>e.textContent.includes('继续课本检测')));
 let card=doc.querySelector('.study-main>.quiz-card');const oldId=card.dataset.attempt;
 check('Answer and scores stay hidden initially',()=>{assert.ok(card.querySelector('.answer.invisible'));assert.ok(card.querySelector('.vote:disabled'));});
 await click(card.querySelector('.word-trigger'));await click(card.querySelector('.vote.good'));
 check('Word flip enables scoring and reveals translation',()=>{assert.equal(card.querySelector('.vote.good').disabled,false);assert.ok(card.querySelector('.vote.good.chosen'));});
 await click([...card.querySelectorAll('button')].find(b=>b.textContent.includes('本部分过关')));
 card=doc.querySelector('.study-main>.quiz-card');
 check('UI pass creates new card and history keeps old card',()=>{assert.notEqual(card.dataset.attempt,oldId);assert.match(card.textContent,/U1 · P2/);assert.equal(doc.querySelector('.history [data-attempt]').dataset.attempt,oldId);});
 const cache=JSON.parse(dom.window.localStorage.getItem('edito-atelier:v1:guest'));
 check('Progress persists to browser storage',()=>{assert.equal(cache.bundle.main.current,1);assert.equal(cache.bundle.main.attempts.length,2);});
 await click([...doc.querySelectorAll('.chapter-map button')].find(b=>b.textContent.includes('P1 · 共同生活')));
 check('Chapter directory opens matching dictionary Part',()=>assert.equal(doc.querySelector('select[aria-label="筛选Part"]').value,'U2P1'));
 dom.window.close();console.log(`${passed} checks passed.`);
}finally{await rm(dir,{recursive:true,force:true});}
